version: "3"

services:
  backend:
    image: "w3ifun/aa_wallet_stackup_bundler_go:latest"
    container_name: "aa_wallet_stackup_bundler_go"
    ports:
      - "4337:4337"
    environment:
      - ERC4337_BUNDLER_ETH_CLIENT_URL=https://polygon-mumbai.blockpi.network/v1/rpc/public
      - ERC4337_BUNDLER_PRIVATE_KEY=43cef1d70bc693e5294ac17febd4025acf8224844ae7c9a72456dc62c795eb9e
      - ERC4337_BUNDLER_SUPPORTED_ENTRY_POINTS=0x081d5B6e93B686cEA78B87f5f96Ec274cC6FFe41
      - ERC4337_BUNDLER_DATA_DIRECTORY=/home/ubuntu/wallet/bundler/stackup-bundler-go-docker/mumbai
      - ERC4337_BUNDLER_GET_LOGS_GAP=1000
    restart: always
