services:
  stackup-bundler-mumbai:
    build:
      context: .
      dockerfile: Dockerfile
    scale: 1
    environment:
      - ERC4337_BUNDLER_ETH_CLIENT_URL=https://polygon-mumbai.blockpi.network/v1/rpc/public
      - ERC4337_BUNDLER_PRIVATE_KEY=43cef1d70bc693e5294ac17febd4025acf8224844ae7c9a72456dc62c795eb9e
      - ERC4337_BUNDLER_SUPPORTED_ENTRY_POINTS=0xD79b0817A1Aeb55042d7b10bD25f99F17239333a,0x081d5B6e93B686cEA78B87f5f96Ec274cC6FFe41
      - ERC4337_BUNDLER_GET_LOGS_GAP=1000
      - ERC4337_BUNDLER_MAX_GASLIMIT=1000000
    command: /app/stackup-bundler start --mode private
    ports:
      - 4337:4337
    volumes:
      - /app/data:/tmp/stackup_bundler
  stackup-bundler-fuji:
    build:
      context: .
      dockerfile: Dockerfile
    scale: 1
    environment:
      - ERC4337_BUNDLER_ETH_CLIENT_URL=https://api.avax-test.network/ext/C/rpc
      - ERC4337_BUNDLER_PRIVATE_KEY=43cef1d70bc693e5294ac17febd4025acf8224844ae7c9a72456dc62c795eb9e
      - ERC4337_BUNDLER_SUPPORTED_ENTRY_POINTS=0x4B63443E5eeecE233AADEC1359254c5C601fB7f4
      - ERC4337_BUNDLER_GET_LOGS_GAP=1000
      - ERC4337_BUNDLER_MAX_GASLIMIT=1000000
    command: /app/stackup-bundler start --mode private
    ports:
      - 4337:4337
    volumes:
      - /app/data:/tmp/stackup_bundler

