name: Okteto Devflow

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  devflow:
    runs-on: ubuntu-latest
    env:
      ENV: dev
    steps:
      - name: checkout
        uses: actions/checkout@master

      - name: context
        uses: okteto/context@latest
        with:
          token: ${{ secrets.OKTETO_TOKEN }}

      - name: "Trigger the pipeline"
        uses: okteto/pipeline@latest
        with:
          name: stackup-bundler
          timeout: 8m
          skipIfExists: false
          namespace: aa-zhangzhishun
          variables: ""